### ISSUE TITLE
complete implimentation of mpris

### ISSUE THREAD

**Issue by user12xxxxxx** [neithern/g4music#78]
i recently shifted to hyprland (using this config https://github.com/end-4/dots-hyprland)
it has this music widget that displays info provided by the player

music player like lollypop provides sufficient info so the widget works properly
![swappy-20240518-215243](https://github.com/neithern/g4music/assets/111512589/30e24d57-c1da-484f-bfb5-99ac662b6d5c)
![Screenshot_2024-05-18_21 49 59](https://github.com/neithern/g4music/assets/111512589/7460ea58-0a13-4a80-b0b2-6ca3f373d827)

but g4music doesn't thus the widget isn't working properly
![swappy-20240518_200048](https://github.com/neithern/g4music/assets/111512589/01431bf8-8dfe-49c5-a377-5ab934626fff)
![Screenshot_2024-05-18_21 51 08](https://github.com/neithern/g4music/assets/111512589/31b77f75-7169-4dd1-8b2b-a8c3ba790a7c)
i asked the hyprdots maintainer (https://github.com/end-4/dots-hyprland/issues/510)

(if the title is wrong let me know)

**Comment by neithern** [comment]
Playing position not show correctly?

**Comment by user12xxxxxx** [comment]
yeah the like how many seconds of song has played

widget ( in case of g4music)
![swappy-20240519-144838](https://github.com/neithern/g4music/assets/111512589/3fda39aa-3720-41f1-919c-e4a807364894)

widget (in case of lollypop)
![swappy-20240519-144855](https://github.com/neithern/g4music/assets/111512589/26d45422-122b-451e-b3a6-84e71d4e9562)

**Comment by neithern** [comment]
It should have been fixed, if you know how to build it, try it please.

**Comment by user12xxxxxx** [comment]
thanks

**Comment by user12xxxxxx** [comment]
hey i built it from the source but now how do i delete it?

**Comment by sam08sk** [comment]
Hello, please let me know if we need to set additional flags to support full MPRIS 
Notice how it doesn't provide this information (trackid). I build from the source but the problem remains.

![Image](https://github.com/user-attachments/assets/f7093597-fe86-4fde-86ed-0177871be13e)

Any help is appreciated.

-Cheers
Sam

**Comment by user12xxxxxx** [comment]
i don't think mpris trackid was implemented

**Comment by user12xxxxxx** [comment]
i'll reopen the issue for  @neithern to see
